version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout

      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -fsSL https://get.docker.com/ | sh
            # curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            # tar -xz -C /tmp -f /tmp/docker-$VER.tg
            # mkdir -p /usr/bi
            # mv /tmp/docker/* /usr/bi

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            # mkdir -p /usr/local/bin/docker-compose
            # sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build service
          command: |
            pwd
            ls
            docker --version
            docker-compose build

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d