version: 2

jobs:
  build:
    machine: true 
      # - image: ubuntu:16.04
      # - image: buildpack-deps:trusty
      # image: circleci/classic:201708-01
    steps:
      - checkout

      - run:
          name: prepare
          command: |
            # apt-get update
            cd $HOME
            sudo apt-get install git
            # export GOROOT=/usr/local/go
            # export GOPATH=$HOME/go
            # export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
            # export PATH=$PATH:/usr/local/bin
            # export PATH=$PATH:/usr/bin
            # echo 'export GOROOT="/usr/local/go"' >> $BASH_ENV
            # echo 'export GOPATH="$HOME/go"' >> $BASH_ENV
            # echo 'export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"' >> $BASH_ENV
            # echo 'export PATH="$PATH:/usr/local/bin"' >> $BASH_ENV
            # echo 'export PATH="$PATH:/usr/bin"' >> $BASH_ENV
            # source $BASH_ENV
            which git
            # export GOPATH=$HOME/go
            # export PATH=$PATH:$GOPATH/bin
            # echo 'export PATH="$GOPATH/bin:$PATH"' >> $BASH_ENV
            echo $HOME
            echo $GOPATH
            git --version
            # apt-get install -y sudo
            # sudo apt-get install -y python-pip
            # apt-get install -y curl
      #       sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      #       sudo apt-key fingerprint 0EBFCD88
      #       sudo add-apt-repository \
      #         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      #         $(lsb_release -cs) \
      #         stable"
      #       sudo apt update
      #       sudo apt install -y docker-ce
      #       sudo pip install -U docker-compose

      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -fsSL https://get.docker.com/ | sh
            # curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            # tar -xz -C /tmp -f /tmp/docker-$VER.tg
            # mkdir -p /usr/bi
            # mv /tmp/docker/* /usr/bi

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/3.2.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            # mkdir -p /usr/local/bin/docker-compose
            # sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build service
          command: |
            pwd
            ls
            docker --version
            docker-compose --version
            # sudo docker-compose build

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            # sudo usermod -aG docker $USER
            # sudo service docker start
            sudo service docker status
            docker ps
            # sudo apt-get remove docker docker-engine
            # curl -sSL https://get.docker.com/ | sh
            docker-compose up -d
            # sudo docker-compose up -d